### ISSUE TITLE
ModuleNotFoundError: No module named 'splinedist.utils'

### ISSUE THREAD

**Issue by carmenrt** [uhlmanngroup/spline-interpolation#1]
i have an error en theres lines of the code: 

$import splinegenerator as sg
$from splinedist.utils import phi_generator, grid_generator, get_contoursize_max, export_imagej_rois
$from splinedist import fill_label_holes, random_label_cmap, calculate_extents, gputools_available
$from splinedist.matching import matching, matching_dataset
$from splinedist.models import Config2D, SplineDist2D, SplineDistData2D

How can I resolve this??

**Comment by sohmandal** [comment]
Hi @carmenrt, which script are you running from this repo that has those lines of the code together and what exact error are you noticing?

**Comment by carmenrt** [comment]
Hello, the notebook is SplineDist_2D_ZeroCostDL4Mic and I can't run this line: **import splinegenerator as sg**

**Comment by sohmandal** [comment]
Hi @carmenrt , thank you for interest in SplineDist. 

From the name of the notebook given by you, I assume that you are trying to use the [ZeroCostDl4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki) version of SplineDist. Please correct me if I am wrong. We are aware that there are certain errors in that notebook, which are happening due to some recent updates in the official release of SplineDist and certain updates in some libraries that ZeroCostDl4Mic uses to design the colab notebooks. Currently we are working on fixing these. 

Meanwhile, please feel to have a look in the [official SplineDist repository](https://github.com/uhlmanngroup/splinedist). This repository contains the latest version of SplinDist. Also we provide data exploration, training, and testing Jupyter notebooks. With this repo the import error that you have encountered before with splinegenerator should be fine. If you encounter any problem with the official SplineDist repo, please feel free to open an issue in that repo. 

cc: @vuhlmann

**Comment by carmenrt** [comment]
I will try with that! Thank you so much!

**Comment by sohmandal** [comment]
You are welcome! 

Closing this issue, please feel free to reopen it or if you have any SplineDist issue, please open an issue in the official SplineDist repository.

**Comment by carmenrt** [comment]
Hello again. I have been looking for the spline dist notebook you told me about. Is training.ipynb?  My idea using the SplineDist notebook from ZeroCost was to perform the task of cell counting on microscopy images.  Thanks!

**Comment by sohmandal** [comment]
Hi! 

If your goal is to do cell counting, I assume you want your first step to be segmentation. Therefore you need to have a trained SplineDist model. If you want to train SplineDist on your dataset, then you need to use [training.ipynb](https://github.com/uhlmanngroup/splinedist/blob/main/training.ipynb). Then you can use your trained model to do the inference on your dataset using [prediction.ipynb](https://github.com/uhlmanngroup/splinedist/blob/main/prediction.ipynb). We also host multiple [pretrained SplineDist models](https://zenodo.org/record/7193306#.Y1EZI9LMJyo) for fluoresence and H&E images, which might be useful depending on your dataset.
